### ISSUE TITLE
Tracker module issue with DM 9.1.0

### ISSUE THREAD

**Issue by babalou** [justingit/dada-mail#543]
Hi Justin,

I'v just installed the new DM 9.1.0 PRO, in CGI mode, on my company server (Apache 2.4.18, PHP 5.5.31, MySQL 5.5.42, PERL 5.10.1). Now, when I try to view the tracker plugin (with Root or List Manager accounts), there's a blank page with this error message :
syntax error at /plugins/tracker line 756, near "." Compilation failed in require at /home/admin05/public_html/cgi-bin/dada//DADA/App.pm line 13371, line 1. 

Tracker module was working perfectly with previous version (9.0.2) installed on the same server.

Do you have any idea ?

Best.

**Comment by justingit** [comment]
Can confirm the bug,
